-- PickBook Supabase schema
-- Run in Supabase SQL Editor before pointing DATABASE_URL at Supabase.

create table if not exists public.books (
    id              bigint generated by default as identity primary key,
    source          text,
    title           text,
    author          text,
    genre           text,
    cover           text,
    download        text,
    language        text,
    synopsis        text,
    chapters_count  integer,
    chapter_content text,
    created_at      timestamptz default now(),
    updated_at      timestamptz default now()
);

alter table public.books enable row level security;

drop policy if exists books_public_read on public.books;
create policy books_public_read on public.books
    for select
    using (true);

create table if not exists public.profiles (
    id                   uuid primary key,
    email                text unique,
    current_plan         text not null default 'free'
                         check (current_plan in ('free', 'standard')),
    paystack_customer_id text,
    subscription_expiry  timestamptz default now(),
    streak_count         integer not null default 0,
    last_read_date       date,
    created_at           timestamptz default now()
);

alter table public.profiles enable row level security;

drop policy if exists profiles_own on public.profiles;
create policy profiles_own on public.profiles
    for all
    using (auth.uid() = id)
    with check (auth.uid() = id);

create table if not exists public.coupons (
    id             bigint generated by default as identity primary key,
    code           text unique not null,
    discount_type  text not null
                   check (discount_type in ('percent', 'fixed_amount', 'free_days')),
    discount_value integer not null check (discount_value >= 0),
    plan_target    text not null default 'standard'
                   check (plan_target in ('standard')),
    max_uses       integer not null default 1 check (max_uses > 0),
    used_count     integer not null default 0 check (used_count >= 0),
    expiry_date    timestamptz,
    created_at     timestamptz default now()
);

alter table public.coupons enable row level security;

create table if not exists public.coupon_claims (
    id         bigint generated by default as identity primary key,
    user_id    uuid references public.profiles(id) on delete cascade,
    coupon_id  bigint references public.coupons(id) on delete cascade,
    claimed_at timestamptz default now(),
    unique (user_id, coupon_id)
);

alter table public.coupon_claims enable row level security;

create table if not exists public.paystack_events (
    id         bigint generated by default as identity primary key,
    reference  text unique not null,
    user_id    uuid references public.profiles(id) on delete cascade,
    plan       text not null check (plan in ('standard')),
    amount     integer not null check (amount >= 0),
    created_at timestamptz default now()
);

alter table public.paystack_events enable row level security;

create table if not exists public.reading_activity (
    id            bigint generated by default as identity primary key,
    user_id       uuid references public.profiles(id) on delete cascade,
    read_date     date not null,
    chapters_read integer not null default 1 check (chapters_read > 0),
    unique (user_id, read_date)
);

alter table public.reading_activity enable row level security;

create index if not exists ix_books_source on public.books(source);
create index if not exists ix_books_genre on public.books(genre);
create index if not exists ix_books_title on public.books(title);
create index if not exists ix_coupons_code on public.coupons(code);
create index if not exists ix_coupon_claims_user_id on public.coupon_claims(user_id);
create index if not exists ix_paystack_events_reference on public.paystack_events(reference);
create index if not exists ix_reading_activity_user_date
    on public.reading_activity(user_id, read_date);
