-- PickBook Supabase schema
-- Run in Supabase SQL Editor before pointing DATABASE_URL at Supabase.
-- This file intentionally mirrors app/models/book.py and includes Storage buckets.

create extension if not exists pgcrypto;

create table if not exists public.books (
    id bigint generated by default as identity primary key,
    source text,
    title text,
    author text,
    genre text,
    cover text,
    download text,
    language text,
    synopsis text,
    chapters_count integer,
    chapter_content text,
    created_at timestamptz default now()
);

create table if not exists public.profiles (
    id text primary key,
    email text unique not null,
    password_hash text,
    email_verified integer not null default 0,
    email_verification_token text,
    email_verification_sent_at timestamptz,
    password_reset_token text,
    password_reset_sent_at timestamptz,
    username text unique,
    author_bio text,
    email_notifications_enabled integer not null default 1,
    author_notifications_enabled integer not null default 1,
    bank_name text,
    bank_account_name text,
    bank_account_number text,
    current_plan text not null default 'free',
    paystack_customer_id text,
    subscription_expiry timestamptz,
    referral_code text unique,
    referred_by text,
    referral_bonus_claimed_at timestamptz,
    signup_fingerprint text,
    terms_accepted_at timestamptz,
    terms_version text,
    streak_count integer not null default 0,
    last_read_date date,
    created_at timestamptz default now()
);

create table if not exists public.coupons (
    id bigint generated by default as identity primary key,
    code text unique not null,
    discount_type text not null,
    discount_value integer not null,
    plan_target text not null default 'standard',
    max_uses integer not null default 1,
    used_count integer not null default 0,
    expiry_date timestamptz,
    created_at timestamptz default now()
);

create table if not exists public.coupon_claims (
    id bigint generated by default as identity primary key,
    user_id text not null,
    coupon_id bigint not null,
    fingerprint text,
    claimed_at timestamptz default now(),
    constraint uq_coupon_claim_user_coupon unique (user_id, coupon_id),
    constraint fk_coupon_claim_profile foreign key (user_id) references public.profiles(id) on delete cascade,
    constraint fk_coupon_claim_coupon foreign key (coupon_id) references public.coupons(id) on delete cascade
);

create table if not exists public.paystack_events (
    id bigint generated by default as identity primary key,
    reference text unique not null,
    user_id text not null,
    plan text not null,
    amount integer not null,
    paystack_fee integer not null default 0,
    net_amount integer not null default 0,
    referral_code text,
    partner_code text,
    created_at timestamptz default now()
);

create table if not exists public.pending_payments (
    reference text primary key,
    kind text not null default 'subscription',
    user_id text,
    plan text,
    amount integer not null,
    metadata_json text,
    processed_at timestamptz,
    created_at timestamptz default now()
);

create table if not exists public.reading_activity (
    id bigint generated by default as identity primary key,
    user_id text not null,
    read_date date not null,
    chapters_read integer not null default 1,
    constraint uq_reading_activity_user_date unique (user_id, read_date)
);

create table if not exists public.stories (
    id bigint generated by default as identity primary key,
    author_id text references public.profiles(id) on delete set null,
    title text not null,
    slug text unique,
    genre text,
    cover text,
    synopsis text,
    status text not null default 'draft',
    review_feedback text,
    published_version_id bigint,
    scheduled_version_id bigint,
    created_at timestamptz default now(),
    updated_at timestamptz,
    reviewed_at timestamptz,
    published_at timestamptz,
    unpublished_at timestamptz
);

create table if not exists public.story_versions (
    id bigint generated by default as identity primary key,
    story_id bigint not null references public.stories(id) on delete cascade,
    version_number integer not null,
    title text not null,
    synopsis text,
    content text,
    status text not null default 'pending_review',
    submitted_at timestamptz,
    reviewed_at timestamptz,
    published_at timestamptz,
    scheduled_for timestamptz,
    created_at timestamptz default now(),
    constraint uq_story_version_number unique (story_id, version_number)
);

create table if not exists public.drafts (
    id bigint generated by default as identity primary key,
    story_id bigint not null references public.stories(id) on delete cascade,
    author_id text references public.profiles(id) on delete set null,
    title text not null,
    synopsis text,
    content text,
    manuscript_metadata_json text,
    created_at timestamptz default now(),
    updated_at timestamptz,
    constraint uq_draft_story_author unique (story_id, author_id)
);

create table if not exists public.reading_progress (
    id bigint generated by default as identity primary key,
    user_id text not null references public.profiles(id) on delete cascade,
    book_id bigint references public.books(id) on delete cascade,
    story_id bigint references public.stories(id) on delete cascade,
    chapter integer not null default 1,
    percent integer not null default 0,
    updated_at timestamptz default now(),
    constraint ck_reading_progress_one_content check (
        (book_id is not null and story_id is null)
        or
        (book_id is null and story_id is not null)
    )
);

create table if not exists public.bookmarks (
    id bigint generated by default as identity primary key,
    user_id text not null references public.profiles(id) on delete cascade,
    book_id bigint references public.books(id) on delete cascade,
    story_id bigint references public.stories(id) on delete cascade,
    chapter integer not null default 1,
    note text,
    created_at timestamptz default now(),
    constraint ck_bookmarks_one_content check (
        (book_id is not null and story_id is null)
        or
        (book_id is null and story_id is not null)
    )
);

create table if not exists public.user_library (
    id bigint generated by default as identity primary key,
    user_id text not null references public.profiles(id) on delete cascade,
    book_id bigint references public.books(id) on delete cascade,
    story_id bigint references public.stories(id) on delete cascade,
    status text not null default 'saved',
    created_at timestamptz default now(),
    constraint ck_user_library_one_content check (
        (book_id is not null and story_id is null)
        or
        (book_id is null and story_id is not null)
    )
);

create table if not exists public.downloads (
    id bigint generated by default as identity primary key,
    user_id text not null references public.profiles(id) on delete cascade,
    book_id bigint references public.books(id) on delete cascade,
    story_id bigint references public.stories(id) on delete cascade,
    device_id text,
    billing_cycle text,
    quota_consumed integer not null default 1,
    created_at timestamptz default now(),
    constraint ck_downloads_one_content check (
        (book_id is not null and story_id is null)
        or
        (book_id is null and story_id is not null)
    )
);

create table if not exists public.search_index (
    id bigint generated by default as identity primary key,
    content_type text not null,
    content_id bigint not null,
    title text not null,
    body text,
    created_at timestamptz default now(),
    updated_at timestamptz,
    constraint ck_search_index_content_type check (content_type in ('book', 'story')),
    constraint uq_search_index_content unique (content_type, content_id)
);

create table if not exists public.reader_engagement (
    id bigint generated by default as identity primary key,
    user_id text not null references public.profiles(id) on delete cascade,
    book_id bigint references public.books(id) on delete cascade,
    story_id bigint references public.stories(id) on delete cascade,
    rating integer,
    liked integer not null default 0,
    comment text,
    comment_status text not null default 'pending_review',
    report_count integer not null default 0,
    report_reason text,
    moderation_note text,
    edited_at timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz,
    constraint ck_reader_engagement_one_content check (
        (book_id is not null and story_id is null)
        or
        (book_id is null and story_id is not null)
    ),
    constraint uq_reader_engagement_user_book unique (user_id, book_id),
    constraint uq_reader_engagement_user_story unique (user_id, story_id)
);

create table if not exists public.story_review_audits (
    id bigint generated by default as identity primary key,
    story_id bigint not null references public.stories(id) on delete cascade,
    admin_id text,
    action text not null,
    from_status text,
    to_status text,
    note text,
    created_at timestamptz default now()
);

create table if not exists public.author_notifications (
    id bigint generated by default as identity primary key,
    author_id text not null references public.profiles(id) on delete cascade,
    story_id bigint references public.stories(id) on delete set null,
    kind text not null,
    title text not null,
    message text,
    read_at timestamptz,
    created_at timestamptz default now()
);

create table if not exists public.author_earnings (
    id bigint generated by default as identity primary key,
    author_id text not null references public.profiles(id) on delete cascade,
    story_id bigint references public.stories(id) on delete set null,
    source text not null default 'manual',
    amount_kobo integer not null default 0,
    status text not null default 'available',
    note text,
    created_at timestamptz default now()
);

create table if not exists public.withdrawal_requests (
    id bigint generated by default as identity primary key,
    author_id text not null references public.profiles(id) on delete cascade,
    amount_kobo integer not null,
    status text not null default 'pending',
    bank_name text,
    bank_account_name text,
    bank_account_number text,
    admin_note text,
    requested_at timestamptz default now(),
    processed_at timestamptz
);

create table if not exists public.author_follows (
    id bigint generated by default as identity primary key,
    reader_id text not null references public.profiles(id) on delete cascade,
    author_id text not null references public.profiles(id) on delete cascade,
    created_at timestamptz default now(),
    constraint uq_author_follow_reader_author unique (reader_id, author_id)
);

create table if not exists public.reader_achievements (
    id bigint generated by default as identity primary key,
    user_id text not null references public.profiles(id) on delete cascade,
    code text not null,
    title text not null,
    description text,
    progress integer not null default 0,
    target integer not null default 1,
    earned_at timestamptz,
    updated_at timestamptz,
    constraint uq_reader_achievement_user_code unique (user_id, code)
);

create table if not exists public.app_settings (
    key text primary key,
    value text,
    updated_at timestamptz default now()
);

create table if not exists public.partner_deals (
    id text primary key,
    name text not null,
    email text unique not null,
    referral_code text unique not null,
    status text not null default 'active',
    created_at timestamptz default now()
);

create table if not exists public.investor_deals (
    id text primary key,
    name text not null,
    email text unique not null,
    plan_type text not null,
    amount integer not null,
    roi_cap_multiplier integer not null default 2,
    status text not null default 'pending_payment',
    created_at timestamptz default now()
);

create index if not exists ix_books_source on public.books(source);
create index if not exists ix_books_genre on public.books(genre);
create index if not exists ix_books_title on public.books(title);
create index if not exists ix_profiles_email on public.profiles(email);
create index if not exists ix_profiles_username on public.profiles(username);
create index if not exists ix_profiles_referral_code on public.profiles(referral_code);
create index if not exists ix_profiles_signup_fingerprint on public.profiles(signup_fingerprint);
create index if not exists ix_profiles_email_verification_token on public.profiles(email_verification_token);
create index if not exists ix_profiles_password_reset_token on public.profiles(password_reset_token);
create index if not exists ix_coupons_code on public.coupons(code);
create index if not exists ix_coupon_claims_user_id on public.coupon_claims(user_id);
create index if not exists ix_coupon_claims_coupon_id on public.coupon_claims(coupon_id);
create index if not exists ix_coupon_claims_fingerprint on public.coupon_claims(fingerprint);
create index if not exists ix_paystack_events_reference on public.paystack_events(reference);
create index if not exists ix_paystack_events_user_id on public.paystack_events(user_id);
create index if not exists ix_paystack_events_referral_code on public.paystack_events(referral_code);
create index if not exists ix_paystack_events_partner_code on public.paystack_events(partner_code);
create index if not exists ix_pending_payments_user_id on public.pending_payments(user_id);
create index if not exists ix_reading_activity_user_date on public.reading_activity(user_id, read_date);
create index if not exists ix_stories_author_id on public.stories(author_id);
create index if not exists ix_stories_slug on public.stories(slug);
create index if not exists ix_stories_status on public.stories(status);
create index if not exists ix_stories_published_version_id on public.stories(published_version_id);
create index if not exists ix_stories_scheduled_version_id on public.stories(scheduled_version_id);
create index if not exists ix_story_versions_story_id on public.story_versions(story_id);
create index if not exists ix_story_versions_status on public.story_versions(status);
create index if not exists ix_drafts_story_id on public.drafts(story_id);
create index if not exists ix_drafts_author_id on public.drafts(author_id);
create index if not exists ix_reading_progress_user_id on public.reading_progress(user_id);
create index if not exists ix_reading_progress_book_id on public.reading_progress(book_id);
create index if not exists ix_reading_progress_story_id on public.reading_progress(story_id);
create index if not exists ix_bookmarks_user_id on public.bookmarks(user_id);
create index if not exists ix_bookmarks_book_id on public.bookmarks(book_id);
create index if not exists ix_bookmarks_story_id on public.bookmarks(story_id);
create index if not exists ix_user_library_user_id on public.user_library(user_id);
create index if not exists ix_user_library_book_id on public.user_library(book_id);
create index if not exists ix_user_library_story_id on public.user_library(story_id);
create index if not exists ix_downloads_user_id on public.downloads(user_id);
create index if not exists ix_downloads_book_id on public.downloads(book_id);
create index if not exists ix_downloads_story_id on public.downloads(story_id);
create index if not exists ix_downloads_device_id on public.downloads(device_id);
create index if not exists ix_downloads_billing_cycle on public.downloads(billing_cycle);
create index if not exists ix_search_index_content_type on public.search_index(content_type);
create index if not exists ix_search_index_content_id on public.search_index(content_id);
create index if not exists ix_reader_engagement_user_id on public.reader_engagement(user_id);
create index if not exists ix_reader_engagement_book_id on public.reader_engagement(book_id);
create index if not exists ix_reader_engagement_story_id on public.reader_engagement(story_id);
create index if not exists ix_reader_engagement_comment_status on public.reader_engagement(comment_status);
create index if not exists ix_story_review_audits_story_id on public.story_review_audits(story_id);
create index if not exists ix_story_review_audits_admin_id on public.story_review_audits(admin_id);
create index if not exists ix_story_review_audits_action on public.story_review_audits(action);
create index if not exists ix_author_notifications_author_id on public.author_notifications(author_id);
create index if not exists ix_author_notifications_story_id on public.author_notifications(story_id);
create index if not exists ix_author_notifications_kind on public.author_notifications(kind);
create index if not exists ix_author_earnings_author_id on public.author_earnings(author_id);
create index if not exists ix_author_earnings_story_id on public.author_earnings(story_id);
create index if not exists ix_author_earnings_source on public.author_earnings(source);
create index if not exists ix_author_earnings_status on public.author_earnings(status);
create index if not exists ix_withdrawal_requests_author_id on public.withdrawal_requests(author_id);
create index if not exists ix_withdrawal_requests_status on public.withdrawal_requests(status);
create index if not exists ix_author_follows_reader_id on public.author_follows(reader_id);
create index if not exists ix_author_follows_author_id on public.author_follows(author_id);
create index if not exists ix_reader_achievements_user_id on public.reader_achievements(user_id);
create index if not exists ix_reader_achievements_code on public.reader_achievements(code);
create index if not exists ix_partner_deals_email on public.partner_deals(email);
create index if not exists ix_partner_deals_referral_code on public.partner_deals(referral_code);
create index if not exists ix_investor_deals_email on public.investor_deals(email);

alter table public.books enable row level security;
alter table public.profiles enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_claims enable row level security;
alter table public.paystack_events enable row level security;
alter table public.pending_payments enable row level security;
alter table public.reading_activity enable row level security;
alter table public.stories enable row level security;
alter table public.story_versions enable row level security;
alter table public.drafts enable row level security;
alter table public.reading_progress enable row level security;
alter table public.bookmarks enable row level security;
alter table public.user_library enable row level security;
alter table public.downloads enable row level security;
alter table public.search_index enable row level security;
alter table public.reader_engagement enable row level security;
alter table public.story_review_audits enable row level security;
alter table public.author_notifications enable row level security;
alter table public.author_earnings enable row level security;
alter table public.withdrawal_requests enable row level security;
alter table public.author_follows enable row level security;
alter table public.reader_achievements enable row level security;
alter table public.app_settings enable row level security;
alter table public.partner_deals enable row level security;
alter table public.investor_deals enable row level security;

drop policy if exists books_public_read on public.books;
create policy books_public_read on public.books for select using (true);

drop policy if exists stories_public_published_read on public.stories;
create policy stories_public_published_read on public.stories for select using (status = 'published');

drop policy if exists profiles_own on public.profiles;
create policy profiles_own on public.profiles
    for all
    using (auth.uid()::text = id)
    with check (auth.uid()::text = id);

drop policy if exists reader_activity_own on public.reading_activity;
create policy reader_activity_own on public.reading_activity
    for all
    using (auth.uid()::text = user_id)
    with check (auth.uid()::text = user_id);

drop policy if exists reading_progress_own on public.reading_progress;
create policy reading_progress_own on public.reading_progress
    for all
    using (auth.uid()::text = user_id)
    with check (auth.uid()::text = user_id);

drop policy if exists bookmarks_own on public.bookmarks;
create policy bookmarks_own on public.bookmarks
    for all
    using (auth.uid()::text = user_id)
    with check (auth.uid()::text = user_id);

drop policy if exists user_library_own on public.user_library;
create policy user_library_own on public.user_library
    for all
    using (auth.uid()::text = user_id)
    with check (auth.uid()::text = user_id);

drop policy if exists downloads_own on public.downloads;
create policy downloads_own on public.downloads
    for all
    using (auth.uid()::text = user_id)
    with check (auth.uid()::text = user_id);

drop policy if exists reader_engagement_public_approved_read on public.reader_engagement;
create policy reader_engagement_public_approved_read on public.reader_engagement
    for select
    using (comment_status = 'approved' or auth.uid()::text = user_id);

drop policy if exists reader_engagement_own_write on public.reader_engagement;
create policy reader_engagement_own_write on public.reader_engagement
    for all
    using (auth.uid()::text = user_id)
    with check (auth.uid()::text = user_id);

drop policy if exists drafts_author_own on public.drafts;
create policy drafts_author_own on public.drafts
    for all
    using (auth.uid()::text = author_id)
    with check (auth.uid()::text = author_id);

drop policy if exists author_notifications_own on public.author_notifications;
create policy author_notifications_own on public.author_notifications
    for select
    using (auth.uid()::text = author_id);

drop policy if exists author_follows_public_read on public.author_follows;
create policy author_follows_public_read on public.author_follows
    for select
    using (true);

drop policy if exists author_follows_own_write on public.author_follows;
create policy author_follows_own_write on public.author_follows
    for all
    using (auth.uid()::text = reader_id)
    with check (auth.uid()::text = reader_id);

drop policy if exists reader_achievements_own on public.reader_achievements;
create policy reader_achievements_own on public.reader_achievements
    for all
    using (auth.uid()::text = user_id)
    with check (auth.uid()::text = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
    ('pickbook-public', 'pickbook-public', true, 52428800, array['image/jpeg', 'image/png', 'image/webp']),
    ('pickbook-private', 'pickbook-private', false, 52428800, array[
        'application/pdf',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'image/jpeg',
        'image/png'
    ])
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists pickbook_public_storage_read on storage.objects;
create policy pickbook_public_storage_read on storage.objects
    for select
    using (bucket_id = 'pickbook-public');

drop policy if exists pickbook_service_storage_all on storage.objects;
create policy pickbook_service_storage_all on storage.objects
    for all
    using (auth.role() = 'service_role' and bucket_id in ('pickbook-public', 'pickbook-private'))
    with check (auth.role() = 'service_role' and bucket_id in ('pickbook-public', 'pickbook-private'));
