-- Chapters: the unit authors create, upload (one at a time or in bulk),
-- edit, rename, reorder, delete, save as draft, and publish.
--
-- Replaces the old behaviour where an author's entire manuscript was
-- collapsed into a single blob on `drafts.content`.

create table if not exists public.chapters (
    id bigint generated by default as identity primary key,
    story_id bigint not null references public.stories(id) on delete cascade,
    author_id text references public.profiles(id) on delete set null,
    title text not null,
    content text,
    position integer not null default 1,
    status text not null default 'draft',
    word_count integer not null default 0,
    original_filename text,
    source_extension text,
    upload_error text,
    created_at timestamptz default now(),
    updated_at timestamptz,
    published_at timestamptz
);

create index if not exists idx_chapters_story_id
    on public.chapters(story_id);

create index if not exists idx_chapters_story_position
    on public.chapters(story_id, position);

create index if not exists idx_chapters_author_id
    on public.chapters(author_id);

alter table if exists public.stories
    add column if not exists original_status text not null default 'standard';

alter table if exists public.books
    add column if not exists original_status text not null default 'standard';

create index if not exists idx_stories_original_status
    on public.stories(original_status);

create index if not exists idx_books_original_status
    on public.books(original_status);
